import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { CompanyScopedPrismaService } from '../prisma/company-scoped-prisma.service';
import { RegisterAdjustmentDto } from './dto/register-adjustment.dto';

// Same pattern as sales.service.ts: the client of
// CompanyScopedPrismaService.forCompany() is a dynamic type generated by
// Prisma Client Extensions, it does not fit Prisma.TransactionClient of the
// base client — the real type of $transaction of THAT client is extracted
// instead of annotating an incompatible generic type.
type CompanyScopedClient = ReturnType<CompanyScopedPrismaService['forCompany']>;
type CompanyScopedTx = Parameters<Parameters<CompanyScopedClient['$transaction']>[0]>[0];

/**
 * Phase 1 (RF-11 / INV-CONS-*): stock queries, read-only.
 * Phase 2 (INV-AJ-*): manual adjustments — adds registerAdjustment().
 * `deductStock()` (moved here from SalesService in Phase 4 of the Online
 * Store, RF-06) is the ONLY automatic stock deduction mechanism of the
 * system — used by both SalesService (in-person sale) and OrdersService
 * (confirming an online order). INV-DISP-01/INV-INV-04: reuse, never
 * duplicate that logic in a second place. A manual adjustment
 * (registerAdjustment) is a different, explicit operation, initiated by a
 * person on a batch they choose — it does not replace or imitate the
 * automatic deduction.
 */
@Injectable()
export class InventoryService {
  constructor(private readonly prismaFactory: CompanyScopedPrismaService) {}

  /**
   * Consolidated stock per product (sum of Lote.cantidad).
   *
   * It does not use Prisma `groupBy`: companyScopeExtension (see
   * prisma/company-scope.extension.ts) only has explicit isolation handling
   * for a fixed set of operations — groupBy is not in that list, so a query
   * with groupBy on a model with empresaId fails explicitly instead of
   * silently skipping the filter (intentional behavior of that extension).
   * Instead of widening that shared file — used by all modules, and its own
   * comment documents why each operation is added there explicitly, not for
   * convenience — this phase computes the consolidated stock in memory from a
   * findMany of Lote (supported), which at this scale (thousands of
   * products, few batches each) is a light query. If the volume grows enough
   * for this to become a real problem, that is the moment to extend
   * companyScopeExtension with groupBy, with its own review — not before.
   */
  async consolidatedStock(
    companyId: string,
    search?: string,
    onlyLowStock?: boolean,
    // Online Store design phase: Familia/Subfamilia filter for the public
    // catalog's category navigation (previously only the free-text search
    // existed) — reused as is by the internal panel if it ever needs the same,
    // without duplicating this query. familiaId filters the whole Familia;
    // subfamiliaId (if sent together) narrows further within that Familia.
    familyId?: string,
    subfamilyId?: string,
  ) {
    const db = this.prismaFactory.forCompany(companyId);

    const whereProduct: Prisma.ProductoWhereInput = {
      activo: true,
      ...(familyId ? { familiaId: familyId } : {}),
      ...(subfamilyId ? { subfamiliaId: subfamilyId } : {}),
      /* eslint-disable indent -- known false positive of the base `indent`
         rule with a ternary returning a nested object (same pattern as
         catalog.controller.ts) */
      ...(search
        ? {
            OR: [
              { nombre: { contains: search, mode: 'insensitive' } },
              { codigoInterno: { contains: search, mode: 'insensitive' } },
            ],
          }
        : {}),
      /* eslint-enable indent */
    };

    // The limit of 50 does not only protect the text search: filtering by a
    // whole Familia (e.g. 'Bebidas') can also bring hundreds of products
    // without this cap — same reason, same limit.
    const limit = !!search || !!familyId || !!subfamilyId;
    const products = await db.producto.findMany({
      where: whereProduct,
      orderBy: { nombre: 'asc' },
      ...(limit ? { take: 50 } : {}),
    });

    const productIds = products.map((p) => p.id);
    const batches = await db.lote.findMany({
      where: { productoId: { in: productIds } },
      select: { productoId: true, cantidad: true },
    });

    const stockByProduct = new Map<string, number>();
    for (const batch of batches) {
      const current = stockByProduct.get(batch.productoId) ?? 0;
      stockByProduct.set(batch.productoId, current + Number(batch.cantidad));
    }

    const result = products.map((product) => {
      const stockTotal = stockByProduct.get(product.id) ?? 0;
      const minimumStock = Number(product.stockMinimo);
      return {
        productoId: product.id,
        nombre: product.nombre,
        codigoInterno: product.codigoInterno,
        familiaId: product.familiaId,
        subfamiliaId: product.subfamiliaId,
        tipoId: product.tipoId,
        subtipoId: product.subtipoId,
        unidadBase: product.unidadBase,
        stockTotal,
        stockMinimo: minimumStock,
        // INV-AL-01: stockMinimo=0 (default of the whole existing catalog, see
        // migration) never triggers the alert — a product without an explicitly
        // configured threshold is not considered 'low stock', even if its
        // stockTotal is also 0.
        stockBajo: minimumStock > 0 && stockTotal <= minimumStock,
      };
    });

    if (!onlyLowStock) {
      return result;
    }
    return result.filter((r) => r.stockBajo);
  }

  /**
   * INV-AL-01/02/03: products with stock below their configured minimum,
   * and batches that expire within the lookahead window (7 days by default
   * — D-09 of the SDD left it as 'initial proposal, pending confirmation';
   * it is implemented as configurable via INVENTARIO_ALERTA_VENCIMIENTO_DIAS
   * instead of fixing it in code, so as not to block the whole phase waiting
   * for that formal confirmation).
   *
   * It does not reuse consolidatedStock() with onlyLowStock=true for the
   * low-stock part: that method has no product limit without `search`, and
   * here the WHOLE catalog explicitly matters (an alert that omits products
   * due to pagination is not a reliable alert).
   */
  async alerts(companyId: string) {
    const db = this.prismaFactory.forCompany(companyId);
    const noticeDays = Number(process.env.INVENTARIO_ALERTA_VENCIMIENTO_DIAS ?? 7);

    const products = await db.producto.findMany({
      where: { activo: true, stockMinimo: { gt: 0 } },
    });
    const productIds = products.map((p) => p.id);
    const batches = await db.lote.findMany({
      where: { productoId: { in: productIds } },
      select: { productoId: true, cantidad: true },
    });
    const stockByProduct = new Map<string, number>();
    for (const batch of batches) {
      const current = stockByProduct.get(batch.productoId) ?? 0;
      stockByProduct.set(batch.productoId, current + Number(batch.cantidad));
    }

    const lowStock = products
      .map((product) => ({
        productoId: product.id,
        nombre: product.nombre,
        codigoInterno: product.codigoInterno,
        stockTotal: stockByProduct.get(product.id) ?? 0,
        stockMinimo: Number(product.stockMinimo),
      }))
      .filter((p) => p.stockTotal <= p.stockMinimo);

    const expiryLimit = new Date();
    expiryLimit.setDate(expiryLimit.getDate() + noticeDays);
    const expiringBatches = await db.lote.findMany({
      where: { vencimiento: { lte: expiryLimit }, cantidad: { gt: 0 } },
      include: { producto: { select: { nombre: true, codigoInterno: true } } },
      orderBy: { vencimiento: 'asc' },
    });

    return {
      diasAnticipacion: noticeDays,
      stockBajo: lowStock,
      lotesPorVencer: expiringBatches.map((batch) => ({
        loteId: batch.id,
        productoId: batch.productoId,
        productoNombre: batch.producto.nombre,
        codigoInterno: batch.producto.codigoInterno,
        numeroLote: batch.numeroLote,
        vencimiento: batch.vencimiento,
        cantidad: batch.cantidad,
      })),
    };
  }

  /**
   * Records a manual adjustment (INV-AJ-01/02/03) on an existing batch.
   * `dto.cantidad` is the variation (positive adds, negative subtracts), not
   * the resulting total.
   *
   * Concurrency (INV-AJ-03): no read-then-write of the current stock is done
   * to decide whether the negative adjustment is valid — that would be
   * vulnerable to two concurrent adjustments reading the same 'old' value
   * and both being created as valid when together they would leave the batch
   * negative. Instead, a conditional UPDATE is executed (updateMany with
   * `cantidad: { gte: -dto.cantidad }` in the WHERE) which the database
   * evaluates atomically against the current value at that instant: if the
   * UPDATE affects 0 rows, the condition was not met (with the data already
   * updated by any other concurrent transaction), and it aborts.
   *
   * Traceability (INV-AJ-02): the MovimientoStock is created in the SAME
   * transaction as the batch UPDATE — never one without the other. There is
   * no path that modifies Lote.cantidad without leaving the movement that
   * explains it.
   */
  async registerAdjustment(companyId: string, dto: RegisterAdjustmentDto, userId: string) {
    const db = this.prismaFactory.forCompany(companyId);

    const batch = await db.lote.findUnique({ where: { id: dto.loteId } });
    if (!batch) {
      throw new NotFoundException('Lote no encontrado');
    }

    return db.$transaction(async (tx) => {
      const result = await this.applyAtomicAdjustment(tx, companyId, dto.loteId, dto.cantidad);
      if (result.count === 0) {
        // The condition `cantidad + dto.cantidad >= 0` was not met (someone else
        // adjusted/deducted this batch between the findUnique above and this
        // point, or the value is no longer enough) — there is nothing to
        // 'retry' automatically: it is real information for whoever is adjusting,
        // not a transient error to hide.
        throw new BadRequestException(
          'El ajuste dejaría el lote con cantidad negativa (puede haber cambiado por otra operación concurrente) — verificá el stock actual y reintentá.',
        );
      }

      return tx.movimientoStock.create({
        data: {
          empresaId: companyId,
          productoId: batch.productoId,
          loteId: dto.loteId,
          tipoMovimiento: dto.cantidad > 0 ? 'Entrada' : 'Salida',
          cantidad: Math.abs(dto.cantidad),
          motivo: `AjusteManual: ${dto.motivo}`,
          usuarioId: userId,
        },
      });
    });
  }

  private async applyAtomicAdjustment(
    tx: CompanyScopedTx,
    companyId: string,
    batchId: string,
    quantity: number,
  ) {
    // Prisma does not support `cantidad: { gte: <expression with the field> }`
    // in a typed updateMany — a parameterized $executeRaw is used (never
    // string interpolation) for the atomic conditional UPDATE. empresaId is
    // explicitly included in the WHERE: $executeRaw does NOT go through
    // companyScopeExtension (that extension only intercepts calls to the normal
    // Prisma Client, not raw SQL), so multi-company isolation here is the
    // responsibility of this query, not of the extension.
    const rows = await tx.$executeRaw(Prisma.sql`
      UPDATE "Lote"
      SET "cantidad" = "cantidad" + ${quantity}, "updatedAt" = now()
      WHERE "id" = ${batchId} AND "empresaId" = ${companyId} AND "cantidad" + ${quantity} >= 0
    `);
    return { count: rows };
  }

  /**
   * Deducts `cantidad` from a product's stock, taking from the available
   * batches in FIFO order by expiry (the batch that expires soonest is
   * consumed first). It must run INSIDE the caller's transaction (creating
   * the sale/confirming the order) — never as a separate step, so that
   * concurrency is protected by the same atomicity (INV-03/INV-06).
   *
   * D-09: expired batches are not filtered out of the selection — an expired
   * batch can still be sold (explicit owner decision, not a block), but
   * every MovimientoStock leaving an already expired batch at the time of
   * the operation is marked with `loteVencidoAlMomento: true`, for permanent
   * audit. It returns `true` if any affected batch was expired, so the
   * caller can build a warning.
   *
   * `reason`/`referenceId` are defined by the caller: 'Venta' + Venta id
   * (SalesService) or 'Venta' + Pedido id (OrdersService, when confirming an
   * online order — it is still a real sale, it just originated through that
   * channel, no new reason is invented).
   *
   * It generates a 'Salida' type MovimientoStock for each affected batch.
   * It rejects the whole operation (rolls back the transaction) if the sum of
   * available quantity across all of the product's batches is not enough —
   * D-09 left this unchanged: insufficient stock is still always rejected,
   * it has no exception/authorization mechanism.
   */
  async deductStock(
    tx: CompanyScopedTx,
    companyId: string,
    productId: string,
    requiredQuantity: number,
    reason: string,
    referenceId: string,
    userId: string | null,
  ): Promise<boolean> {
    const batches = await tx.lote.findMany({
      where: { empresaId: companyId, productoId: productId, cantidad: { gt: 0 } },
      orderBy: { vencimiento: 'asc' },
    });

    const stockTotal = batches.reduce((acc, l) => acc + Number(l.cantidad), 0);
    if (stockTotal < requiredQuantity) {
      throw new BadRequestException(
        `Stock insuficiente para el producto ${productId}: disponible ${stockTotal}, requerido ${requiredQuantity}`,
      );
    }

    const now = new Date();
    let remaining = requiredQuantity;
    let hadExpiredBatch = false;
    for (const batch of batches) {
      if (remaining <= 0) break;
      const thisBatchQuantity = Math.min(remaining, Number(batch.cantidad));
      const expiredBatch = batch.vencimiento <= now;
      if (expiredBatch) {
        hadExpiredBatch = true;
      }

      await tx.lote.update({
        where: { id: batch.id },
        data: { cantidad: { decrement: thisBatchQuantity } },
      });

      await tx.movimientoStock.create({
        data: {
          empresaId: companyId,
          productoId: productId,
          loteId: batch.id,
          tipoMovimiento: 'Salida',
          cantidad: thisBatchQuantity,
          motivo: reason,
          referenciaId: referenceId,
          usuarioId: userId,
          loteVencidoAlMomento: expiredBatch,
        },
      });

      remaining -= thisBatchQuantity;
    }

    return hadExpiredBatch;
  }
}
