import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { CompanyScopedPrismaService } from '../prisma/company-scoped-prisma.service';
import { CreateSupplierDto } from './dto/create-supplier.dto';
import { UpdateSupplierDto } from './dto/update-supplier.dto';
import { CreatePurchaseDto } from './dto/create-purchase.dto';
import { ReceivePurchaseDto } from './dto/receive-purchase.dto';
import { CreateSupplierPaymentDto } from './dto/create-supplier-payment.dto';
import { CreateSupplierReturnDto } from './dto/create-supplier-return.dto';

// Same pattern as sales.service.ts / inventory.service.ts: the client of
// CompanyScopedPrismaService.forCompany() is a dynamic type generated by
// Prisma Client Extensions, it does not fit Prisma.TransactionClient of the
// base client.
type CompanyScopedClient = ReturnType<CompanyScopedPrismaService['forCompany']>;
type CompanyScopedTx = Parameters<Parameters<CompanyScopedClient['$transaction']>[0]>[0];

/**
 * RF-12 (purchases and suppliers), Phase 1 of the agreed scope: CRUD of
 * Proveedor, create/issue a Compra, and confirm its receipt (total or
 * partial) generating real Lote + MovimientoStock.
 *
 * Outside this phase (see docs/scaffolding-notas.md): supplier payments,
 * attaching invoices/documentation, supplier returns. RF-12 asks to
 * 'keep cost history per product and purchase' — CompraItem.costoUnitario
 * already records it, nothing separate is added yet.
 */
@Injectable()
export class PurchasesService {
  constructor(private readonly prismaFactory: CompanyScopedPrismaService) {}

  // --- Proveedores -------------------------------------------------

  async listSuppliers(companyId: string) {
    const db = this.prismaFactory.forCompany(companyId);
    return db.proveedor.findMany({ orderBy: { nombre: 'asc' } });
  }

  async createSupplier(companyId: string, dto: CreateSupplierDto) {
    const db = this.prismaFactory.forCompany(companyId);
    // Explicit Prisma.ProveedorUncheckedCreateInput: without this annotation,
    // through the generic type returned by companyScopeExtension, TypeScript
    // cannot resolve the Exact<XOR<...>> that Prisma requires for `create`
    // (same pattern as catalog.controller.ts with Producto). empresaId is still
    // passed here (redundant with what the extension injects, but same
    // criterion already used in sales.service.ts: more explicit in code that
    // ends up in the database, less 'trusting the extension's magic').
    const data: Prisma.ProveedorUncheckedCreateInput = { ...dto, empresaId: companyId };
    return db.proveedor.create({ data });
  }

  async updateSupplier(companyId: string, id: string, dto: UpdateSupplierDto) {
    const db = this.prismaFactory.forCompany(companyId);
    const existing = await db.proveedor.findUnique({ where: { id } });
    if (!existing) {
      throw new NotFoundException('Proveedor no encontrado');
    }
    return db.proveedor.update({ where: { id }, data: dto });
  }

  // --- Compras -------------------------------------------------------

  async listPurchases(companyId: string) {
    const db = this.prismaFactory.forCompany(companyId);
    return db.compra.findMany({
      include: { items: true, proveedor: true },
      orderBy: { fechaOrden: 'desc' },
    });
  }

  async getPurchase(companyId: string, id: string) {
    const db = this.prismaFactory.forCompany(companyId);
    const purchase = await db.compra.findUnique({
      where: { id },
      include: { items: true, proveedor: true, recepciones: true },
    });
    if (!purchase) {
      throw new NotFoundException('Compra no encontrada');
    }
    return purchase;
  }

  /**
   * Creates the purchase order in BORRADOR status. It does not reserve or
   * modify stock — that only happens in receivePurchase(). Like
   * SalesService.create(), products are resolved BEFORE the transaction so
   * the whole order can be validated at once.
   *
   * TODO: it does not validate duplicate productoId within dto.items — a
   * Compra with two CompraItem of the same product is valid today in the
   * schema (without @@unique([compraId, productoId])) but has no clear use
   * case and complicates receivePurchase() by not being able to assume 'one
   * product, one item'. The constraint is not added without confirming that
   * allowing it is really unnecessary (e.g. two different batches of the
   * same product in a single order).
   */
  async createPurchase(companyId: string, dto: CreatePurchaseDto, userId: string) {
    const db = this.prismaFactory.forCompany(companyId);

    const supplier = await db.proveedor.findUnique({ where: { id: dto.proveedorId } });
    if (!supplier) {
      throw new NotFoundException('Proveedor no encontrado');
    }

    const productIds = [...new Set(dto.items.map((i) => i.productoId))];
    const products = await db.producto.findMany({ where: { id: { in: productIds } } });
    const existingProductIds = new Set(products.map((p) => p.id));
    for (const item of dto.items) {
      if (!existingProductIds.has(item.productoId)) {
        throw new NotFoundException(`Producto ${item.productoId} no encontrado`);
      }
    }

    const total = dto.items.reduce(
      (acc, item) => acc + item.cantidadPedida * item.costoUnitario,
      0,
    );

    const data: Prisma.CompraUncheckedCreateInput = {
      empresaId: companyId,
      proveedorId: dto.proveedorId,
      usuarioId: userId,
      estado: 'BORRADOR',
      total,
      fechaRecepcionEsperada: dto.fechaRecepcionEsperada,
      items: {
        create: dto.items.map((item) => ({
          productoId: item.productoId,
          cantidadPedida: item.cantidadPedida,
          costoUnitario: item.costoUnitario,
        })),
      },
    };
    return db.compra.create({ data, include: { items: true } });
  }

  /**
   * BORRADOR -> EMITIDA. Explicit step, separate from createPurchase(): a
   * draft order can still be reviewed/corrected (there is no edit endpoint
   * yet, but the status leaves it prepared) before being considered sent to
   * the supplier. Only a Compra in BORRADOR can be issued — re-issuing an
   * already issued or received one makes no sense.
   */
  async issuePurchase(companyId: string, id: string) {
    const purchase = await this.getPurchase(companyId, id);
    if (purchase.estado !== 'BORRADOR') {
      throw new BadRequestException(
        `Solo se puede emitir una compra en estado BORRADOR (actual: ${purchase.estado})`,
      );
    }
    const db = this.prismaFactory.forCompany(companyId);
    return db.compra.update({ where: { id }, data: { estado: 'EMITIDA' } });
  }

  /**
   * Confirms the receipt of goods (RF-12: 'receive goods totally or
   * partially... the physical intake must update the stock when the receipt
   * is confirmed'). For each received item:
   * - Validates that no more than what is missing is received (cantidadPedida
   *   - cantidadRecibida accumulated from previous receipts) — D-10:
   *   'receipt differences are identified', a receipt that leaves
   *   cantidadRecibida > cantidadPedida is not allowed unless that is a
   *   separate business decision (not implemented).
   * - Creates a new Lote with the data declared in the DTO.
   * - Creates an 'Entrada' type MovimientoStock, reason Compra, linked to the
   *   RecepcionCompra (same mechanism SalesService uses for Salida/Venta —
   *   stock movement logic is not duplicated).
   * - Updates CompraItem.cantidadRecibida (accumulated).
   * - Recomputes Compra.estado: RECIBIDA if all items are complete,
   *   RECEPCION_PARCIAL if any is missing.
   *
   * All inside a single $transaction — a receipt that is partial in number
   * of items must never leave the stock and the purchase status out of sync
   * with each other.
   */
  async receivePurchase(
    companyId: string,
    purchaseId: string,
    dto: ReceivePurchaseDto,
    userId: string,
  ) {
    const purchase = await this.getPurchase(companyId, purchaseId);
    if (purchase.estado !== 'EMITIDA' && purchase.estado !== 'RECEPCION_PARCIAL') {
      throw new BadRequestException(
        `No se puede recibir mercadería de una compra en estado ${purchase.estado}`,
      );
    }

    const itemsById = new Map(purchase.items.map((item) => [item.id, item]));
    for (const receipt of dto.items) {
      const item = itemsById.get(receipt.compraItemId);
      if (!item) {
        throw new NotFoundException(`El item ${receipt.compraItemId} no pertenece a esta compra`);
      }
      const pendingQuantity = Number(item.cantidadPedida) - Number(item.cantidadRecibida);
      if (receipt.cantidadRecibida > pendingQuantity) {
        throw new BadRequestException(
          `El item ${receipt.compraItemId} tiene ${pendingQuantity} unidades pendientes, no se pueden recibir ${receipt.cantidadRecibida}`,
        );
      }
    }

    const db = this.prismaFactory.forCompany(companyId);
    return db.$transaction(async (tx) => {
      const receptionPayload: Prisma.RecepcionCompraUncheckedCreateInput = {
        empresaId: companyId,
        compraId: purchaseId,
        usuarioId: userId,
        observaciones: dto.observaciones,
      };
      const reception = await tx.recepcionCompra.create({ data: receptionPayload });

      for (const receipt of dto.items) {
        const item = itemsById.get(receipt.compraItemId)!;

        const batchPayload: Prisma.LoteUncheckedCreateInput = {
          empresaId: companyId,
          productoId: item.productoId,
          numeroLote: receipt.numeroLote,
          vencimiento: new Date(receipt.vencimiento),
          cantidad: receipt.cantidadRecibida,
        };
        const batch = await tx.lote.create({ data: batchPayload });

        await tx.movimientoStock.create({
          data: {
            empresaId: companyId,
            productoId: item.productoId,
            loteId: batch.id,
            tipoMovimiento: 'Entrada',
            cantidad: receipt.cantidadRecibida,
            motivo: 'Compra',
            referenciaId: purchaseId,
            usuarioId: userId,
            recepcionCompraId: reception.id,
          },
        });

        await tx.compraItem.update({
          where: { id: item.id },
          data: { cantidadRecibida: { increment: receipt.cantidadRecibida } },
        });
      }

      const newStatus = await this.calculateStatusAfterReception(tx, purchaseId);
      await tx.compra.update({ where: { id: purchaseId }, data: { estado: newStatus } });

      return tx.recepcionCompra.findUniqueOrThrow({
        where: { id: reception.id },
        include: { movimientosStock: true },
      });
    });
  }

  private async calculateStatusAfterReception(tx: CompanyScopedTx, purchaseId: string) {
    const items = await tx.compraItem.findMany({ where: { compraId: purchaseId } });
    const allComplete = items.every(
      (item) => Number(item.cantidadRecibida) >= Number(item.cantidadPedida),
    );
    return allComplete ? 'RECIBIDA' : 'RECEPCION_PARCIAL';
  }

  // --- Pagos a proveedor -------------------------------------------

  async listPayments(companyId: string, purchaseId: string) {
    const purchase = await this.getPurchase(companyId, purchaseId);
    const db = this.prismaFactory.forCompany(companyId);
    return db.pagoProveedor.findMany({
      where: { compraId: purchase.id },
      orderBy: { fecha: 'desc' },
    });
  }

  /**
   * Records a partial or total payment against a Compra and recomputes
   * totalPagado + saldo of the Compra within the same transaction.
   * Paying more than what is owed (current balance) is not allowed.
   */
  async createPayment(
    companyId: string,
    purchaseId: string,
    dto: CreateSupplierPaymentDto,
    userId: string,
  ) {
    const purchase = await this.getPurchase(companyId, purchaseId);
    const currentBalance = Number(purchase.saldo ?? purchase.total);
    if (dto.monto > currentBalance + 0.001) {
      throw new BadRequestException(
        `El monto ($${dto.monto}) supera el saldo pendiente ($${currentBalance.toFixed(2)})`,
      );
    }

    const db = this.prismaFactory.forCompany(companyId);
    return db.$transaction(async (tx) => {
      const payment = await tx.pagoProveedor.create({
        data: {
          empresaId: companyId,
          compraId: purchaseId,
          proveedorId: purchase.proveedorId,
          usuarioId: userId,
          monto: dto.monto,
          medioPago: dto.medioPago,
          referencia: dto.referencia,
          notas: dto.notas,
        } as Prisma.PagoProveedorUncheckedCreateInput,
      });

      const newTotalPaid = Number(purchase.totalPagado) + dto.monto;
      const newBalance = Number(purchase.total) - newTotalPaid;
      await tx.compra.update({
        where: { id: purchaseId },
        data: { totalPagado: newTotalPaid, saldo: Math.max(0, newBalance) },
      });

      return payment;
    });
  }

  // --- Devoluciones a proveedor ------------------------------------

  async listReturns(companyId: string, purchaseId: string) {
    const purchase = await this.getPurchase(companyId, purchaseId);
    const db = this.prismaFactory.forCompany(companyId);
    return db.devolucionProveedor.findMany({
      where: { compraId: purchase.id },
      include: { items: true },
      orderBy: { fecha: 'desc' },
    });
  }

  /**
   * Records a return of goods to the supplier. For each item:
   * - Validates that the batch (if specified) belongs to the product.
   * - Generates a Salida/Devolucion MovimientoStock.
   * - Reduces the Lote quantity.
   * It does not reduce the Compra total (the debt stays the same — the
   * return is negotiated with the supplier as a credit note or discount on
   * a future purchase, outside the system for now).
   */
  async createReturn(
    companyId: string,
    purchaseId: string,
    dto: CreateSupplierReturnDto,
    userId: string,
  ) {
    const purchase = await this.getPurchase(companyId, purchaseId);
    const db = this.prismaFactory.forCompany(companyId);

    return db.$transaction(async (tx) => {
      const returnRecord = await tx.devolucionProveedor.create({
        data: {
          empresaId: companyId,
          compraId: purchaseId,
          proveedorId: purchase.proveedorId,
          usuarioId: userId,
          motivo: dto.motivo,
          items: {
            create: dto.items.map((item) => ({
              productoId: item.productoId,
              loteId: item.loteId,
              cantidad: item.cantidad,
              costoUnitario: item.costoUnitario,
            })),
          },
        } as Prisma.DevolucionProveedorUncheckedCreateInput,
        include: { items: true },
      });

      // Generate a 'Salida' MovimientoStock for each returned item
      for (const item of dto.items) {
        await tx.movimientoStock.create({
          data: {
            empresaId: companyId,
            productoId: item.productoId,
            loteId: item.loteId,
            tipoMovimiento: 'Salida',
            cantidad: item.cantidad,
            motivo: 'Devolucion',
            referenciaId: returnRecord.id,
            usuarioId: userId,
          },
        });

        // Reduce the batch quantity if one was specified
        if (item.loteId) {
          await tx.lote.update({
            where: { id: item.loteId },
            data: { cantidad: { decrement: item.cantidad } },
          });
        }
      }

      return returnRecord;
    });
  }
}
