import { Type } from 'class-transformer';
import { ArrayMinSize, IsArray, IsIn, IsOptional, IsUUID, ValidateNested } from 'class-validator';
import { CreateSaleItemDto } from './create-sale-item.dto';

const VALID_CHANNELS = ['presencial', 'mayorista', 'online'] as const;

/* eslint-disable indent */
export class CreateSaleDto {
  @IsIn(VALID_CHANNELS)
  canal: (typeof VALID_CHANNELS)[number];

  @IsOptional()
  @IsUUID()
  clienteId?: string;

  @IsArray()
  @ArrayMinSize(1)
  @ValidateNested({ each: true })
  @Type(() => CreateSaleItemDto)
  items: CreateSaleItemDto[];

  // Inc-1 (INV-VTA-07): UUID v4 generated by the frontend before confirming.
  // Retrying with the same key returns the already created sale without
  // duplicating stock.
  @IsOptional()
  @IsUUID()
  idempotencyKey?: string;
}
